# Generated by Django 5.1.1 on 2024-09-30 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_facture', models.DateField(auto_now_add=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PAID', 'Payé'), ('UNPAID', 'Non payé')], default='UNPAID', max_length=20)),
                ('expediteur_nom', models.CharField(max_length=100)),
                ('expediteur_telephone', models.CharField(max_length=15)),
                ('recepteur_nom', models.CharField(max_length=100)),
                ('recepteur_telephone', models.CharField(max_length=15)),
                ('type_fret', models.CharField(default='Aérien', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colis.client')),
                ('colis', models.ManyToManyField(to='colis.colis')),
            ],
        ),
    ]
