# Generated by Django 5.1.1 on 2024-10-04 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colis', '0002_facture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colis',
            name='entrepot',
        ),
        migrations.AlterField(
            model_name='colis',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_destination', to='colis.entrepot'),
        ),
        migrations.AlterField(
            model_name='colis',
            name='origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colis_origine', to='colis.entrepot'),
        ),
        migrations.DeleteModel(
            name='Facture',
        ),
    ]
